name: Curaçao Deal Check

on:
  schedule:
    - cron: '0 9,17 * * *' # Draait elke dag om 09:00 en 17:00
  workflow_dispatch: # Hiermee kun je hem handmatig starten

jobs:
  check-deals:
    runs-on: ubuntu-latest
    steps:
      - name: Code ophalen
        uses: actions/checkout@v3

      - name: Python instellen
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Afhankelijkheden installeren
        run: |
          pip install playwright requests beautifulsoup4
          playwright install chromium

      - name: Run script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python Curacaodeal.py
